apiVersion: apps/v1
kind: Deployment
metadata:
  name: solo-project-deployment
  labels:
    app: solo-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solo-project
  template:
    metadata:
      labels:
        app: solo-project
    spec:
      containers:
        - name: solo-project-deployment
          image: pglenn/solo-project
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
