name: run-tests
on:
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - run: npm ci
      - run: touch .env
      - run: echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
      - run: echo TEST_PORT=${{ secrets.TEST_PORT }} >> .env
      - run: npm test
