name: run-tests
on:
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: |
          cd server
          touch .env 
          echo MONGO_URI=${{ vars.MONGO_URI }} >> .env
          echo TEST_PORT=5050 >> .env
          echo PORT=3000 >> .env
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: test server
        run: |
          npm ci
          npm test
      - name: test client
        run: |
          cd ../server
          npm ci 
          npm test
